"""Add reflex_local_auth tables

Revision ID: f7a2b3c91ce8
Revises: 70461a4f8f57
Create Date: 2025-11-15 09:46:13.675530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a2b3c91ce8'
down_revision: Union[str, Sequence[str], None] = '70461a4f8f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_localauthsession_session_id', table_name='localauthsession')
    op.drop_index('ix_localauthsession_user_id', table_name='localauthsession')
    op.drop_table('localauthsession')
    op.drop_index('ix_localuser_username', table_name='localuser')
    op.drop_table('localuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.BLOB(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localuser_username', 'localuser', ['username'], unique=1)
    op.create_table('localauthsession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expiration', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localauthsession_user_id', 'localauthsession', ['user_id'], unique=False)
    op.create_index('ix_localauthsession_session_id', 'localauthsession', ['session_id'], unique=1)
    # ### end Alembic commands ###
